#site conf
title: JUG (JVM User Group) - Milano
description: Benvenuto sul sito del <span>JUG Milano</span>!

#user profile
user_name: jugmilano
twitter: jugmilano
github: jugmilano
linkedin: groups/JUG-Milano-78141
gplus: 104844775136245946302/posts

highlighter: pygments
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
